By default, Micronaut's controllers produce JSON. Usually, you consume those endpoints with a mobile phone
application or a Javascript front end (Angular, React, Vue.js ...). However, to keep this guide simple we are
going to produce HTML in our controllers.

In order to do that, we use http://velocity.apache.org[Apache Velocity].
____
Velocity is a Java-based template engine. It permits anyone to use a simple yet powerful template language to reference objects defined in Java code.
____

Add a dependency to https://docs.micronaut.io/latest/guide/index.html#views[Server Side View Rendering Module] and to Velocity:

[source,groovy]
.build.gradle
----
dependencies {
...
..
.
include::{sourceDir}/build.gradle[tag=velocity]
}
----

Create two velocity templates in `src/main/resources/views`:

[source,groovy]
.src/main/resources/views/home.vm
----
include::{sourceDir}/src/main/resources/views/home.vm[]
----

[source,groovy]
.src/main/resources/views/auth.vm
----
include::{sourceDir}/src/main/resources/views/auth.vm[]
----

To render those templates, create `VelocityService.kotlin`

[source,kotlin]
.src/main/kotlin/example/micronaut/services/VelocityService.kt
----
include::{sourceDir}/src/main/kotlin/example/micronaut/services/VelocityService.kt[]
----

<1> To create a Sigleton bean use the `javax.inject.Singleton` annotation.
<2> Use the `javax.annotation.PostConstruct` annotation to trigger the method execution after dependency injection is done. Typically to perform any initialization.